{% set name = "pytest-reportportal" %}
{% set version = "5.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-reportportal-{{ version }}.tar.gz
  sha256: d024fd90289e9519f9c1612e03491a9324b191ee66aa3474dfe04fffe0539be2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill >=0.2.7.1
    - pytest >=3.8.0
    - python >=3.6
    - reportportal-client >=5.0.12
    - six >=1.15.0

test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
